# source:
# - https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  release:
    types:
    - created

# jobs:
#   build:
#     strategy:
#       matrix:
#         os: [macos-latest, ubuntu-latest, windows-latest]
#     runs-on: ${{ matrix.os }}
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Install Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: 10.x
#     - run: npm install
#     - run: xvfb-run -a npm test
#       if: runner.os == 'Linux'
#     - run: npm test
#       if: runner.os != 'Linux'

#   publish:
#   - name: Publish
#     if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
#     run: npm run deploy
#     env:
#       VSCE_PAT: ${{ secrets.VSCE_PAT }}

# on:
#   push:
#     branches:
#       - master
name: Deploy VSCode Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_PAT"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
